# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'CityWeatherForecastApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  inhibit_all_warnings!
  
  pod 'AFNetworking', '~> 2.5.4'

  target 'CityWeatherForecastAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
